/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/_admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/_admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/_admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/_admin.orders'
import { Route as AdminCustomersRouteImport } from './routes/_admin.customers'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin.analytics'
import { Route as AdminAgentsRouteImport } from './routes/_admin.agents'
import { Route as AdminProductsWelcomeKitsRouteImport } from './routes/_admin.products.welcome-kits'
import { Route as AdminProductsNewCollectionRouteImport } from './routes/_admin.products.new-collection'
import { Route as AdminProductsB2bRouteImport } from './routes/_admin.products.b2b'
import { Route as AdminOrdersStatusRouteImport } from './routes/_admin.orders.status'
import { Route as AdminOrdersSamplesRouteImport } from './routes/_admin.orders.samples'
import { Route as AdminOrdersIdRouteImport } from './routes/_admin.orders.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsWelcomeKitsRoute =
  AdminProductsWelcomeKitsRouteImport.update({
    id: '/welcome-kits',
    path: '/welcome-kits',
    getParentRoute: () => AdminProductsRoute,
  } as any)
const AdminProductsNewCollectionRoute =
  AdminProductsNewCollectionRouteImport.update({
    id: '/new-collection',
    path: '/new-collection',
    getParentRoute: () => AdminProductsRoute,
  } as any)
const AdminProductsB2bRoute = AdminProductsB2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersStatusRoute = AdminOrdersStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersSamplesRoute = AdminOrdersSamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/agents': typeof AdminAgentsRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/customers': typeof AdminCustomersRoute
  '/orders': typeof AdminOrdersRouteWithChildren
  '/payments': typeof AdminPaymentsRoute
  '/products': typeof AdminProductsRouteWithChildren
  '/reviews': typeof AdminReviewsRoute
  '/settings': typeof AdminSettingsRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/orders/samples': typeof AdminOrdersSamplesRoute
  '/orders/status': typeof AdminOrdersStatusRoute
  '/products/b2b': typeof AdminProductsB2bRoute
  '/products/new-collection': typeof AdminProductsNewCollectionRoute
  '/products/welcome-kits': typeof AdminProductsWelcomeKitsRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AdminAgentsRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/customers': typeof AdminCustomersRoute
  '/orders': typeof AdminOrdersRouteWithChildren
  '/payments': typeof AdminPaymentsRoute
  '/products': typeof AdminProductsRouteWithChildren
  '/reviews': typeof AdminReviewsRoute
  '/settings': typeof AdminSettingsRoute
  '/': typeof AdminIndexRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/orders/samples': typeof AdminOrdersSamplesRoute
  '/orders/status': typeof AdminOrdersStatusRoute
  '/products/b2b': typeof AdminProductsB2bRoute
  '/products/new-collection': typeof AdminProductsNewCollectionRoute
  '/products/welcome-kits': typeof AdminProductsWelcomeKitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/agents': typeof AdminAgentsRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/orders': typeof AdminOrdersRouteWithChildren
  '/_admin/payments': typeof AdminPaymentsRoute
  '/_admin/products': typeof AdminProductsRouteWithChildren
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/orders/$id': typeof AdminOrdersIdRoute
  '/_admin/orders/samples': typeof AdminOrdersSamplesRoute
  '/_admin/orders/status': typeof AdminOrdersStatusRoute
  '/_admin/products/b2b': typeof AdminProductsB2bRoute
  '/_admin/products/new-collection': typeof AdminProductsNewCollectionRoute
  '/_admin/products/welcome-kits': typeof AdminProductsWelcomeKitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/customers'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reviews'
    | '/settings'
    | '/orders/$id'
    | '/orders/samples'
    | '/orders/status'
    | '/products/b2b'
    | '/products/new-collection'
    | '/products/welcome-kits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/analytics'
    | '/customers'
    | '/orders'
    | '/payments'
    | '/products'
    | '/reviews'
    | '/settings'
    | '/'
    | '/orders/$id'
    | '/orders/samples'
    | '/orders/status'
    | '/products/b2b'
    | '/products/new-collection'
    | '/products/welcome-kits'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/agents'
    | '/_admin/analytics'
    | '/_admin/customers'
    | '/_admin/orders'
    | '/_admin/payments'
    | '/_admin/products'
    | '/_admin/reviews'
    | '/_admin/settings'
    | '/_admin/'
    | '/_admin/orders/$id'
    | '/_admin/orders/samples'
    | '/_admin/orders/status'
    | '/_admin/products/b2b'
    | '/_admin/products/new-collection'
    | '/_admin/products/welcome-kits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reviews': {
      id: '/_admin/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments': {
      id: '/_admin/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/agents': {
      id: '/_admin/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products/welcome-kits': {
      id: '/_admin/products/welcome-kits'
      path: '/welcome-kits'
      fullPath: '/products/welcome-kits'
      preLoaderRoute: typeof AdminProductsWelcomeKitsRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_admin/products/new-collection': {
      id: '/_admin/products/new-collection'
      path: '/new-collection'
      fullPath: '/products/new-collection'
      preLoaderRoute: typeof AdminProductsNewCollectionRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_admin/products/b2b': {
      id: '/_admin/products/b2b'
      path: '/b2b'
      fullPath: '/products/b2b'
      preLoaderRoute: typeof AdminProductsB2bRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/_admin/orders/status': {
      id: '/_admin/orders/status'
      path: '/status'
      fullPath: '/orders/status'
      preLoaderRoute: typeof AdminOrdersStatusRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/_admin/orders/samples': {
      id: '/_admin/orders/samples'
      path: '/samples'
      fullPath: '/orders/samples'
      preLoaderRoute: typeof AdminOrdersSamplesRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/_admin/orders/$id': {
      id: '/_admin/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersSamplesRoute: typeof AdminOrdersSamplesRoute
  AdminOrdersStatusRoute: typeof AdminOrdersStatusRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersSamplesRoute: AdminOrdersSamplesRoute,
  AdminOrdersStatusRoute: AdminOrdersStatusRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsB2bRoute: typeof AdminProductsB2bRoute
  AdminProductsNewCollectionRoute: typeof AdminProductsNewCollectionRoute
  AdminProductsWelcomeKitsRoute: typeof AdminProductsWelcomeKitsRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsB2bRoute: AdminProductsB2bRoute,
  AdminProductsNewCollectionRoute: AdminProductsNewCollectionRoute,
  AdminProductsWelcomeKitsRoute: AdminProductsWelcomeKitsRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
